### ISSUE TITLE
[Enhancement] Tooltip activation for all model icons on homepage chart

### ISSUE THREAD

**Issue by fakezeta** [JonathanChavezTamales/LLMStats#4]
First things first 😄 : thank you for your great work!

It would be useful to enable the tooltip on the homepage chart for all models when hovering over their icon, not only for the "edge" ones.

**Comment by JonathanChavezTamales** [comment]
Thanks for the feedback!

I'm submitting a fix now that changes the library I use (recharts) to a new one for more custom behaviors (echarts).
Should be online soon.

<img width="1036" alt="image" src="https://github.com/user-attachments/assets/f9e97ce5-d923-4c22-900e-802bf368dc6b" />

**Comment by JonathanChavezTamales** [comment]
This is before, just for reference.

<img width="1083" alt="image" src="https://github.com/user-attachments/assets/e3a832a8-e489-4d2d-a93b-607104cc2316" />
