### ISSUE TITLE
Request: Increase table width

### ISSUE THREAD

**Issue by sammcj** [JonathanChavezTamales/LLMStats#5]
Love the initiative and that you've open sourced it.

Something I noticed right away was how narrow the table containing the information you want to read is:

<img width="3096" alt="image" src="https://github.com/user-attachments/assets/89ed009a-c57e-4699-a4ad-42927361c00a">

This screenshot isn't even with the browser maximised, it's at about 70% of the available OS width.

This means not only a lot of wasted screen real estate but also horizontal scrolling.

I suspect it was designed for mobile devices and not desktops which I could understand - but given that most model selection and downloading is done on desktop devices it might make sense to make the table width responsive - perhaps something like 80% of the browsers width?

e.g. https://userstyles.world/style/19611/llm-stats-com

**Comment by dagbdagb** [comment]
Fully agree.

**Comment by JonathanChavezTamales** [comment]
I code from a Macbook so I didn't notice. Thanks for the feedback!

Should be fixed now.
<img width="1226" alt="image" src="https://github.com/user-attachments/assets/08949eb8-6f99-4432-9d35-67690f030bbc" />

**Comment by sammcj** [comment]
Nice, thanks for that!

**Comment by sammcj** [comment]
Just checked - it's the same still, if you try it on a 4k monitor you'll see this:

<img width="3776" alt="image" src="https://github.com/user-attachments/assets/592cd3e7-30fe-4200-96e0-5e3cf5c46a2b" />

And this is on my 2023 Macbook Pro 16, it's a better on the small screen but still pretty squashed:

<img width="2054" alt="image" src="https://github.com/user-attachments/assets/708882e8-8406-4e9d-a7fd-475708c3e99e" />

**Comment by sammcj** [comment]
For reference, if I create a style override like this:

```css
@-moz-document url-prefix("https://llm-stats.com") {
  .container {
    max-width: 2400px;
  }
}
```

It seems to fix it:

<img width="2405" alt="image" src="https://github.com/user-attachments/assets/cff98134-f712-4389-a057-031cbe77d7b8" />

**Comment by JonathanChavezTamales** [comment]
My bad, I hadn't deployed. This is how it should look like now in prod:

<img width="785" alt="image" src="https://github.com/user-attachments/assets/cb8ae0c6-c0d2-499f-81c4-e390c4e3e9dd" />

I decided to add keep some bit of padding at the sides. I hope this one works now! Thanks for letting me know
