### ISSUE TITLE
Dark mode?

### ISSUE THREAD

**Issue by clduab11** [JonathanChavezTamales/LLMStats#8]
I'm sure it's a bit complicated given the graphing information and some of the color reverses, but is it possible to implement a dark mode?

I love this leaderboard and use it in conjunction with Hugging Face for model testing constantly. It's sometimes a bit difficult to use being very light-eyed and having above-average light sensitivity. No worries if it's unable to be done, as I'll definitely continue to use it nonetheless! :)

**Comment by JonathanChavezTamales** [comment]
Thanks for your feedback. I'll add it

<img width="1186" alt="image" src="https://github.com/user-attachments/assets/4d64fb5a-d9f4-4086-a260-90b50bf5fe7e" />

**Comment by clduab11** [comment]
Thanks so much; looks great! I sure do appreciate it!
